# Generated by Django 4.2.3 on 2023-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy_tools', '0007_alter_privacypolicy_confirm_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicyconfirmation',
            name='second_confirmed_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Second confirmed at'),
        ),
    ]
