# Generated by Django 4.2.3 on 2023-09-22 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy_tools', '0008_privacypolicyconfirmation_second_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, verbose_name='Token')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privacy_policy_tools.privacypolicyconfirmation', verbose_name='Confirmation')),
            ],
            options={
                'verbose_name': 'One Time Token',
                'verbose_name_plural': 'One Time Tokens',
            },
        ),
    ]
